// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sales.API.Data;

#nullable disable

namespace ParcialEstadio.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParcialEstadio.Shared.Entities.Boleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaUso")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<int?>("PorteriaId")
                        .HasColumnType("int");

                    b.Property<bool>("Usada")
                        .HasMaxLength(100)
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PorteriaId");

                    b.ToTable("Boletas");
                });

            modelBuilder.Entity("ParcialEstadio.Shared.Entities.Porteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Porterias");
                });

            modelBuilder.Entity("ParcialEstadio.Shared.Entities.Boleta", b =>
                {
                    b.HasOne("ParcialEstadio.Shared.Entities.Porteria", "Porteria")
                        .WithMany()
                        .HasForeignKey("PorteriaId");

                    b.Navigation("Porteria");
                });
#pragma warning restore 612, 618
        }
    }
}
